'use strict';
const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
const colors={Walls:'#52605a',Furniture:'#658879','Windows & Doors':'#538c97',Carpentry:'#967453',Kitchen:'#a17b50',Electrical:'#cf9750',Plumbing:'#4f91b7',Appliances:'#7e80ae',Lighting:'#c7a43c',Measurements:'#718078',Annotations:'#374e65'};
const catalog=[['Wall polygon','Walls',0,0,'polygon'],['Room outline','Walls',0,0,'polygon',false,true],['Single door','Windows & Doors',.9,.9,'door'],['2-panel sliding','Windows & Doors',1.2,.15,'sliding2'],['3-panel sliding','Windows & Doors',1.8,.15,'sliding3'],['2-panel casement','Windows & Doors',1.2,.6,'casement2'],['3-panel casement','Windows & Doors',1.8,.6,'casement3'],['Tall bookshelf','Furniture',.8,.3,'bookshelf'],['Chest of drawers','Furniture',.8,.45,'drawers'],['Bench','Furniture',1.2,.4,'bench'],['Chair','Furniture',.45,.45,'chair'],['Stool','Furniture',.35,.35,'stool'],['Sofa','Furniture',2.1,.9,'sofa'],['King bed','Furniture',1.83,1.9,'bed'],['Bedside table','Furniture',.45,.4,'smalltable'],['Queen bed','Furniture',1.52,1.9,'bed'],['Single bed','Furniture',.91,1.9,'bed'],['Dining table','Furniture',1.4,.8,'table'],['Wardrobe','Furniture',1.8,.6,'cabinet'],['Custom carpentry','Carpentry',0,0,'polygon'],['Rectangular carpentry','Carpentry',1.2,.6,'carpentry'],['Overhead storage','Carpentry',1.2,.35,'overhead'],['Custom overhead','Carpentry',0,0,'polygon',true],['Desk','Furniture',1.2,.6,'table'],['Armchair','Furniture',.8,.8,'sofa'],['Fridge','Kitchen',.7,.7,'cabinet'],['Oven','Kitchen',.6,.6,'oven'],['Tall unit','Kitchen',.6,.6,'tallunit'],['Kitchen sink','Kitchen',.8,.5,'sink'],['Stove','Kitchen',.6,.52,'stove'],['TV console','Furniture',1.8,.4,'console'],['Washing machine','Appliances',.6,.6,'washer'],['Ceiling fan','Appliances',1.2,1.2,'ceilingfan'],['Wall fan','Appliances',.4,.45,'wallfan'],['Dryer','Appliances',.6,.6,'dryer'],['Steigen','Appliances',1.2,.6,'steigen'],['Power socket','Electrical',.18,.18,'socket'],['Light switch','Electrical',.15,.15,'switch'],['Data point','Electrical',.18,.18,'data'],['DB box','Electrical',.4,.15,'cabinet'],['Cable route','Electrical',0,0,'route'],['Sink','Plumbing',.6,.5,'sink'],['Toilet','Plumbing',.4,.7,'toilet'],['Shower','Plumbing',.9,.9,'shower'],['Water point','Plumbing',.15,.15,'round'],['Cold water pipe','Plumbing',0,0,'route'],['Hot water pipe','Plumbing',0,0,'route'],['Indoor unit','Appliances',.9,.23,'aircon'],['Compressor','Appliances',.7,.7,'compressor'],['Refrigerant route','Appliances',0,0,'route'],['Wall light','Lighting',.2,.15,'walllight'],['Ceiling light','Lighting',.3,.3,'light'],['Downlight','Lighting',.12,.12,'light'],['Pendant','Lighting',.4,.4,'light'],['LED strip','Lighting',0,0,'route']];
let state={version:1,name:'My HDB home',width:1000,height:850,ppm:100,calibrated:true,demo:true,image:null,opacity:.8,items:[],layers:Object.fromEntries(Object.keys(colors).map(k=>[k,true]))};
let selected=null,category='Furniture',mode='select',pending=null,points=[],view={x:-100,y:-70,w:1200,h:990},drag=null,history=[],future=[],hover=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const status=s=>$('status').textContent=s;
function checkpoint(){history.push(JSON.stringify(state));if(history.length>40)history.shift();future=[];}
function modeSet(m){mode=m;points=[];pending=null;hover=null;$('polygon-controls').hidden=m!=='polygon';$('finish-polygon').disabled=m!=='polygon';$('undo-corner').disabled=m!=='polygon';$('select').classList.toggle('active',m==='select');$('calibrate').classList.toggle('active',m==='calibrate');$('measure').classList.toggle('active',m==='measure');$('text-tool').classList.toggle('active',m==='text');$('canvas').style.cursor=m==='select'?'default':'crosshair';render();}
function symbol(type,w,h,c,showText=true){let body='';const rect=(x,y,a,b,r=2)=>`<rect x="${x}" y="${y}" width="${a}" height="${b}" rx="${r}"/>`;
if(type==='sofa')body=rect(0,0,w,h,7)+rect(w*.1,h*.12,w*.8,h*.25)+`<path d="M${w/2} ${h*.4}v${h*.52}M${w*.1} ${h*.42}v${h*.5}M${w*.9} ${h*.42}v${h*.5}"/>`;
else if(type==='bed')body=rect(0,0,w,h,3)+rect(w*.08,h*.06,w*.38,h*.2)+rect(w*.54,h*.06,w*.38,h*.2)+`<path d="M0 ${h*.34}H${w}M${w*.08} ${h*.38}v${h*.55}h${w*.84}v-${h*.55}"/>`;
else if(type==='table')body=rect(0,0,w,h,10)+`<path d="M${w*.15} 0v${h}M${w*.85} 0v${h}" opacity=".3"/>`;
else if(type==='cabinet')body=rect(0,0,w,h)+`<path d="M${w/2} 0v${h}M${w*.43} ${h*.4}v${h*.2}M${w*.57} ${h*.4}v${h*.2}"/>`;
else if(type==='carpentry')body=rect(0,0,w,h,0)+`<path d="M0 ${h*.2}H${w}M${w*.33} ${h*.2}V${h}M${w*.67} ${h*.2}V${h}"/>`;
else if(type==='overhead-polygon')body=`<path d="M0 0H${w}V${h*.4}H${w*.4}V${h}H0Z" fill="none" stroke-dasharray="1 5" stroke-linecap="round"/>`;
else if(type==='polygon')body=`<path d="M0 0H${w}V${h*.4}H${w*.4}V${h}H0Z"/>`;
else if(type==='bookshelf')body=rect(0,0,w,h,1)+`<g fill="none">${[.33,.66].map(y=>`<path d="M0 ${h*y}H${w}"/>`).join('')}<path d="M${w*.12} ${h*.08}V${h*.29}M${w*.22} ${h*.08}V${h*.29}M${w*.32} ${h*.08}L${w*.4} ${h*.29}M${w*.6} ${h*.4}V${h*.62}M${w*.72} ${h*.4}V${h*.62}M${w*.15} ${h*.76}H${w*.45}M${w*.15} ${h*.85}H${w*.45}"/></g>`;
else if(type==='drawers')body=rect(0,0,w,h,2)+`<g fill="none">${[0,1,2].map(n=>`${rect(w*.08,h*(.07+n*.3),w*.84,h*.26,1)}<path d="M${w*.4} ${h*(.2+n*.3)}H${w*.6}"/>`).join('')}</g>`;
else if(type==='smalltable')body=rect(w*.05,h*.08,w*.9,h*.12,2)+rect(w*.1,h*.2,w*.8,h*.66,2)+rect(w*.18,h*.28,w*.64,h*.24,1)+`<path d="M${w*.42} ${h*.4}H${w*.58}M${w*.18} ${h*.61}H${w*.82}M${w*.2} ${h*.86}V${h}M${w*.8} ${h*.86}V${h}"/>`;
else if(type==='console')body=rect(0,h*.1,w,h*.75,2)+`<g fill="none">${rect(w*.05,h*.23,w*.28,h*.48,1)}${rect(w*.37,h*.23,w*.25,h*.48,1)}${rect(w*.66,h*.23,w*.29,h*.21,1)}${rect(w*.66,h*.5,w*.29,h*.21,1)}</g><path d="M${w*.08} ${h*.47}H${w*.3}M${w*.77} ${h*.34}H${w*.84}M${w*.77} ${h*.61}H${w*.84}M${w*.12} ${h*.85}V${h}M${w*.88} ${h*.85}V${h}"/>`;
else if(type==='ceilingfan'||type==='wallfan'){const sy=type==='wallfan'?.78:1;body=`<g transform="translate(${w/2} ${h*sy/2}) scale(${w/100} ${h*sy/100})">${type==='wallfan'?'<circle r="46" fill="none"/><circle r="40" fill="none" opacity=".4"/>':''}${[0,120,240].map(a=>`<path transform="rotate(${a})" d="M-5 -7C-30 -18 -21 -44 -9 -44C5 -44 11 -22 5 -7Z"/>`).join('')}<circle r="8" fill="white"/></g>${type==='wallfan'?`<path d="M${w*.45} ${h*.75}V${h*.94}H${w*.55}V${h*.75}"/>${rect(w*.25,h*.94,w*.5,h*.06,1)}`:''}`;}
else if(type==='walllight')body=`<path d="M${w*.1} 0H${w*.9}M${w*.5} 0V${h*.2}M${w*.2} ${h*.25}H${w*.8}L${w*.95} ${h*.68}H${w*.05}Z"/><path d="M${w*.25} ${h*.82}L${w*.15} ${h}M${w*.5} ${h*.82}V${h}M${w*.75} ${h*.82}L${w*.85} ${h}"/>`;
else if(type==='bench')body=rect(0,h*.12,w,h*.76,2)+`<path d="M${w*.12} 0v${h*.12}M${w*.88} 0v${h*.12}M${w*.12} ${h*.88}v${h*.12}M${w*.88} ${h*.88}v${h*.12}"/>`;
else if(type==='chair')body=rect(w*.12,h*.18,w*.76,h*.7,4)+rect(w*.05,0,w*.9,h*.2,2)+`<path d="M${w*.2} ${h*.88}V${h}M${w*.8} ${h*.88}V${h}"/>`;
else if(type==='stool')body=`<circle cx="${w/2}" cy="${h/2}" r="${Math.min(w,h)*.42}"/><path d="M${w*.15} ${h*.15}l${w*.12} ${h*.12}M${w*.85} ${h*.15}l-${w*.12} ${h*.12}M${w*.15} ${h*.85}l${w*.12} -${h*.12}M${w*.85} ${h*.85}l-${w*.12} -${h*.12}"/>`;
else if(type==='washer'||type==='dryer')body=rect(0,0,w,h,1)+(`<text x="${w/2}" y="${h/2}" text-anchor="middle" dominant-baseline="central" font-family="Arial" font-size="${Math.min(w,h)*.52}" font-weight="600" stroke="none" fill="${c}">${type==='washer'?'W':'D'}</text>`);
else if(type==='steigen')body=rect(0,0,w,h,1)+[.25,.5,.75].map(y=>`<path d="M${w*.12} ${h*y}H${w*.88}"/>`).join('');
else if(type==='overhead')body=`<rect width="${w}" height="${h}" fill="none" stroke-dasharray="1 5" stroke-linecap="round"/>`;
else if(type==='sliding2'||type==='sliding3'){const n=type==='sliding2'?2:3,pw=w/n;body=rect(0,0,w,h,0)+`<path d="M0 ${h*.5}H${w}"/>`+Array.from({length:n},(_,j)=>{const x=j*pw,y=j%2?h*.55:h*.12,dir=j%2?-1:1,cx=x+pw*.5;return `${rect(x+pw*.03,y,pw*.94,h*.33,0)}<path d="M${cx-dir*pw*.18} ${y+h*.16}H${cx+dir*pw*.18}l${-dir*pw*.08} -${h*.08}m${dir*pw*.08} ${h*.08}l${-dir*pw*.08} ${h*.08}" fill="none"/>`;}).join('');}
else if(type==='casement2'||type==='casement3'){const n=type==='casement2'?2:3,pw=w/n;body=rect(0,h*.9,w,h*.1,0)+Array.from({length:n},(_,j)=>{const x=j*pw,hinge=x+(j===n-1?pw:0),end=x+(j===n-1?0:pw);return `<path d="M${x} ${h*.9}H${x+pw}M${hinge} ${h*.9}V0" fill="none"/><path d="M${hinge} 0A${pw} ${h*.9} 0 0 ${j===n-1?0:1} ${end} ${h*.9}" fill="none" stroke-dasharray="3 3"/><circle cx="${hinge}" cy="${h*.9}" r="1.8"/>`;}).join('');}
else if(type==='door')body=`<path d="M0 0V${h}H${w}" fill="none"/><path d="M0 0A${w} ${h} 0 0 1 ${w} ${h}" fill="none" stroke-dasharray="4 3"/><circle cx="0" cy="${h}" r="2"/>`;
else if(type==='tallunit')body=rect(0,0,w,h,0)+`<path d="M0 0L${w} ${h}M${w} 0L0 ${h}"/>`;
else if(type==='oven')body=rect(0,0,w,h)+rect(w*.1,h*.25,w*.8,h*.65)+`<path d="M${w*.2} ${h*.14}H${w*.8}"/>`;
else if(type==='stove')body=rect(0,0,w,h)+[.28,.72].flatMap(x=>[.28,.72].map(y=>`<ellipse cx="${w*x}" cy="${h*y}" rx="${w*.14}" ry="${h*.14}"/>`)).join('');
else if(type==='aircon')body=rect(0,0,w,h,Math.min(w,h)*.15)+`<path d="M${w*.07} ${h*.28}H${w*.93}M${w*.09} ${h*.57}H${w*.91}L${w*.86} ${h*.85}H${w*.14}Z" fill="none"/>${[.67,.76].map(y=>`<path d="M${w*.16} ${h*y}H${w*.84}"/>`).join('')}<circle cx="${w*.88}" cy="${h*.43}" r="${Math.min(w*.015,h*.055)}" fill="${c}" stroke="none"/>`;
else if(type==='compressor'){const size=Math.min(w,h),cx=w*.43,cy=h*.5;body=rect(0,0,w,h,size*.06)+`<g transform="translate(${cx} ${cy}) scale(${size*.007})"><circle r="46" fill="none"/><circle r="40" fill="none" opacity=".45"/>${[0,120,240].map(a=>`<path transform="rotate(${a})" d="M-5 -7C-30 -18 -21 -35 -9 -35C5 -35 11 -22 5 -7Z"/>`).join('')}<circle r="7" fill="white"/></g>${[.27,.39,.51,.63,.75].map(y=>`<path d="M${w*.83} ${h*y}H${w*.93}"/>`).join('')}`;}
else if(type==='sink')body=rect(0,0,w,h,5)+rect(w*.12,h*.2,w*.76,h*.68,7)+`<path d="M${w/2} 0v${h*.3}"/>`;
else if(type==='toilet')body=rect(0,0,w,h*.3)+`<ellipse cx="${w/2}" cy="${h*.64}" rx="${w*.43}" ry="${h*.34}"/>`;
else if(type==='shower')body=rect(0,0,w,h)+`<path d="M0 0L${w} ${h}M${w} 0L0 ${h}" opacity=".5"/>`;
else {body=`<ellipse cx="${w/2}" cy="${h/2}" rx="${w*.46}" ry="${h*.46}"/>`;if(type==='light')body+=`<path d="M${w*.18} ${h*.18}L${w*.82} ${h*.82}M${w*.82} ${h*.18}L${w*.18} ${h*.82}"/>`;if(type==='socket')body+=`<path d="M${w*.35} ${h*.3}v${h*.4}M${w*.65} ${h*.3}v${h*.4}"/>`;if(showText&&(type==='switch'||type==='data'))body+=`<text x="${w/2}" y="${h*.68}" font-size="${h*.5}" text-anchor="middle" stroke="none" fill="${c}">${type==='switch'?'S':'D'}</text>`;}
return `<g fill="${c}18" stroke="${c}" stroke-width="1.7" vector-effect="non-scaling-stroke">${body}</g>`;}
function demoPlan(){return `<rect width="1000" height="850" fill="white"/><g fill="#f7f8f5" stroke="#58675e" stroke-width="8"><path d="M80 90H920V730H80Z"/><path d="M80 350H340V90M340 350V490M340 570V730M80 530H250M310 530H340M340 280H560M640 280H920M650 90V280M760 280V450H920M650 280V400M650 480V730M650 520H920"/></g><g stroke="#a8b9b0" stroke-width="3" fill="none"><path d="M145 90h125m100 0h210m135 0h125M920 550v130M80 570v90M410 730h170"/><path d="M340 490a80 80 0 0 1-80 80h80M560 280a80 80 0 0 0 80 80v-80M650 400a80 80 0 0 1 80 80h-80" stroke-width="1.5"/></g><g font-family="Arial,sans-serif" font-size="13" fill="#8a978f" text-anchor="middle" letter-spacing="2"><text x="210" y="215">BEDROOM 2</text><text x="493" y="185">BEDROOM 3</text><text x="785" y="185">MAIN BEDROOM</text><text x="810" y="380">BATH</text><text x="210" y="445">KITCHEN</text><text x="210" y="640">SERVICE YARD</text><text x="495" y="475">LIVING / DINING</text><text x="785" y="620">ENTRY</text></g>`;}
function isHotPipe(i){return i.category==='Plumbing'&&(i.hotWater===true||i.label==='Hot water pipe');}
function itemSvg(i,selection=true){const c=isHotPipe(i)?'#d64545':colors[i.category];
if(i.type==='polygon'){const b=polygonBounds(i.points);return `<g data-id="${i.id}"><polygon points="${i.points.map(p=>p.x+','+p.y).join(' ')}" fill="${i.category==='Walls'?(i.room?'none':c):i.overhead?c+'10':c+'35'}" ${i.overhead?'stroke-dasharray="1 5" stroke-linecap="round"':''} stroke="${selected===i.id&&selection?'#17694d':c}" stroke-width="${i.room?(i.wallThickness||.1)*state.ppm:2}" stroke-linejoin="miter"/>${selection&&selected===i.id?i.points.map((p,n)=>`<circle data-vertex="${n}" cx="${p.x}" cy="${p.y}" r="${snapTolerance()/2}" fill="white" stroke="#17694d" stroke-width="2"/>`).join(''):''}${i.showLabel===false?'':`<text x="${(b.minX+b.maxX)/2}" y="${b.maxY+17}" text-anchor="middle" font-family="Arial" font-size="12" fill="${c}" stroke="white" stroke-width="3" paint-order="stroke">${esc(i.label)}</text>`}</g>`;}
if(i.type==='text'){
const size=i.fontSize||20,width=Math.max(size,i.label.length*size*.65);return `<g data-id="${i.id}" transform="translate(${i.x} ${i.y}) rotate(${i.angle})"><rect x="${-width/2-6}" y="${-size/2-6}" width="${width+12}" height="${size+12}" fill="transparent" ${selection&&selected===i.id?'stroke="#17694d" stroke-dasharray="5 3"':''}/>${i.showLabel===false?'':`<text text-anchor="middle" dominant-baseline="central" font-family="Arial" font-size="${size}" font-weight="600" fill="${c}" stroke="white" stroke-width="3" paint-order="stroke">${esc(i.label)}</text>`}</g>`;}
if(i.category==='Measurements'&&i.points?.length===2){const [a,b]=i.points,dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy),nx=len?-dy/len*7:0,ny=len?dx/len*7:7;return `<g data-id="${i.id}"><path d="M${a.x} ${a.y}L${b.x} ${b.y}" stroke="transparent" stroke-width="20"/><path d="M${a.x} ${a.y}L${b.x} ${b.y}M${a.x-nx} ${a.y-ny}L${a.x+nx} ${a.y+ny}M${b.x-nx} ${b.y-ny}L${b.x+nx} ${b.y+ny}" fill="none" stroke="${selection&&selected===i.id?'#17694d':c}" stroke-width="2"/>${i.showLabel===false?'':`<text x="${(a.x+b.x)/2}" y="${(a.y+b.y)/2-12}" text-anchor="middle" font-family="Arial" font-size="14" fill="${c}" stroke="white" stroke-width="4" paint-order="stroke">${i.label&&i.label!=='Measurement'?esc(i.label)+' · ':''}${(len/state.ppm).toFixed(2)} m</text>`}</g>`;}
if(i.points){let d=i.points.map((p,n)=>(n?'L':'M')+p.x+' '+p.y).join(' ');const length=i.points.slice(1).reduce((s,p,n)=>s+Math.hypot(p.x-i.points[n].x,p.y-i.points[n].y),0)/state.ppm;const p=i.points[Math.floor(i.points.length/2)];return `<g data-id="${i.id}"><path d="${d}" stroke="transparent" stroke-width="18" fill="none"/><path d="${d}" stroke="${selection&&i.id===selected&&!isHotPipe(i)?'#17694d':c}" stroke-width="${i.category==='Measurements'?2:4}" fill="none" stroke-linejoin="round" ${isHotPipe(i)?'stroke-dasharray="9 5"':''}/>${i.points.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="3" fill="${c}"/>`).join('')}${i.showLabel===false?'':`<text x="${p.x+8}" y="${p.y-10}" font-family="Arial" font-size="12" fill="${c}" stroke="white" stroke-width="3" paint-order="stroke">${esc(i.label)} · ${length.toFixed(2)} m</text>`}</g>`;}
const w=i.w*state.ppm,h=i.h*state.ppm;return `<g data-id="${i.id}" transform="translate(${i.x} ${i.y}) rotate(${i.angle})"><rect x="${-w/2-5}" y="${-h/2-5}" width="${w+10}" height="${h+10}" rx="5" fill="transparent" ${selection&&selected===i.id?'stroke="#17694d" stroke-width="2" stroke-dasharray="5 3"':''}/><g transform="translate(${-w/2} ${-h/2})">${symbol(i.type,w,h,c,i.showLabel!==false)}</g>${i.showLabel===false?'':`<text x="0" y="${h/2+17}" text-anchor="middle" font-family="Arial" font-size="11" fill="#53675b" stroke="white" stroke-width="3" paint-order="stroke">${esc(i.label)}</text>`}</g>`;}
function art(selection=true){return `<rect width="${state.width}" height="${state.height}" fill="white"/><g opacity="${state.opacity}">${state.image?`<image href="${state.image}" width="${state.width}" height="${state.height}"/>`:demoPlan()}</g>${state.items.filter(i=>state.layers[i.category]).sort((a,b)=>Number(b.category==='Walls')-Number(a.category==='Walls')).map(i=>itemSvg(i,selection)).join('')}`;}
function render(){const svg=$('canvas');svg.setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`);svg.innerHTML=art()+polygonPreview()+ (points.length?`<polyline points="${points.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="#17694d" stroke-width="3"/>${points.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="5" fill="#17694d"/>`).join('')}`:'');$('zoom-label').textContent=Math.round((state.width+200)/view.w*100)+'%';$('undo').disabled=!history.length;$('redo').disabled=!future.length;$('plan-state').textContent=state.demo?'Illustrative 4-room plan':'Your uploaded floor plan';$('scale-status').textContent=(state.demo?'Demo scale':state.calibrated?'Calibrated':'Scale not set')+' · '+state.ppm.toFixed(1)+' px / m';$('scale-title').textContent=state.demo?'Demo scale':state.calibrated?'Scale calibrated':'Set your scale';$('scale-description').textContent=state.calibrated&&!state.demo?'Furniture and measurements now use your calibrated wall length.':'Upload your own plan and calibrate it with a known wall measurement.';}
function library(){ $('categories').innerHTML=Object.keys(colors).filter(c=>c!=='Measurements'&&c!=='Annotations').map(c=>`<button class="${c===category?'active':''}" data-category="${c}">${c}</button>`).join('');const entries=catalog.filter(i=>i[1]===category);$('item-count').textContent=entries.length+' ITEMS';$('catalog').innerHTML=entries.map(i=>`<button data-catalog="${catalog.indexOf(i)}" title="${i[4]==='polygon'?'Draw your own shape':i[4]==='route'?'Draw a route':`${i[2]} × ${i[3]} m`}"><svg viewBox="0 0 65 40">${i[4]==='route'?`<path d="M8 32V12H52V30" fill="none" stroke="${i[0]==='Hot water pipe'?'#d64545':colors[category]}" stroke-width="2"/>`:`<g transform="translate(12 3)">${symbol(i[5]?'overhead-polygon':i[4],40,32,colors[category])}</g>`}</svg>${i[0]}</button>`).join('');}
function layers(){ $('layers').innerHTML=Object.keys(colors).map(c=>`<label class="layer"><span><i class="layer-color" style="background:${colors[c]}"></i>${c}</span><input type="checkbox" data-layer="${c}" ${state.layers[c]?'checked':''} aria-label="Show ${c}"></label>`).join('');}
function properties(){const i=state.items.find(i=>i.id===selected);$('polygon-controls').hidden=mode!=='polygon'&&i?.type!=='polygon';$('finish-polygon').disabled=mode!=='polygon';$('undo-corner').disabled=mode!=='polygon';$('properties').hidden=!i;$('empty-selection').hidden=!!i;if(!i)return;$('wall-thickness-row').hidden=!i.room;$('prop-wall-thickness').value=i.wallThickness||.1;$('prop-label').value=i.label;$('prop-show-label').checked=i.showLabel!==false;$('text-size-row').hidden=i.type!=='text';$('prop-font-size').value=i.fontSize||20;$('size-fields').hidden=i.type==='text'||!!i.points;for(const [key,field] of [['w','width'],['h','height'],['angle','angle']]){$('prop-'+field).value=i[key]??0;$('prop-'+field).disabled=!!i.points;}$('route-length').textContent=i.type==='polygon'?'Drag the shape to move it; drag a corner to reshape. Use the grid and corner snapping controls above the plan.':i.points?(i.category==='Measurements'?'Distance: '+(i.points.slice(1).reduce((s,p,n)=>s+Math.hypot(p.x-i.points[n].x,p.y-i.points[n].y),0)/state.ppm).toFixed(2)+' m. Drag to move; redraw to change endpoints.':'Drag the route to move it. Delete and redraw to change its shape.'):i.type==='text'?'Drag to position your room label.':'';}
function fit(){view={x:-70,y:-65,w:state.width+140,h:state.height+130};render();}
function locationOf(e){let p=$('canvas').createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform($('canvas').getScreenCTM().inverse());}
function finishRoute(){if(points.length<2){status('Add at least two route points.');return;}if(mode==='measure'&&Math.hypot(points[1].x-points[0].x,points[1].y-points[0].y)<1){points=[];render();status('Choose two different points to measure.');return;}checkpoint();const i={id:uid(),label:pending?.[0]||'Measurement',category:pending?.[1]||'Measurements',hotWater:pending?.[0]==='Hot water pipe',points:points.map(p=>({x:p.x,y:p.y}))};state.items.push(i);state.layers[i.category]=true;selected=i.id;modeSet('select');layers();properties();status(i.category==='Measurements'?'Measurement label added. Edit its label or drag to move.':'Route added. Select it to move, rename or delete.');}
$('canvas').addEventListener('pointerdown',e=>{if(e.button!==0&&e.button!==1)return;let p=locationOf(e);if(e.button===1||e.altKey){drag={pan:true,x:e.clientX,y:e.clientY,view:{...view}};$('canvas').setPointerCapture(e.pointerId);e.preventDefault();return;}if(p.x<0||p.y<0||p.x>state.width||p.y>state.height)return;
if(mode==='polygon'){p=snapPoint(p,e);if(points.length>=3&&Math.hypot(p.x-points[0].x,p.y-points[0].y)<=snapTolerance()){finishPolygon();return;}if(e.detail===2){finishPolygon();return;}if(!points.length||Math.hypot(p.x-points.at(-1).x,p.y-points.at(-1).y)>.01)points.push({x:p.x,y:p.y});hover=null;render();status('Click corners. Click the first point or Finish shape to close. Shift keeps an edge straight.');return;}
if(mode==='calibrate'||mode==='measure'||mode==='route'){if(e.detail===2&&mode==='route'){finishRoute();return;}points.push({x:p.x,y:p.y});render();if(mode==='calibrate'&&points.length===2){if(Math.hypot(points[1].x-points[0].x,points[1].y-points[0].y)<5){points=[];render();status('Choose two distinct points on a wall.');return;}$('scale-dialog').showModal();}else if(mode==='measure'&&points.length===2)finishRoute();else status(mode==='route'?'Click to add bends. Double-click or press Enter to finish.':'Click the other end of the wall.');return;}
if(mode==='text'){checkpoint();const i={id:uid(),type:'text',category:'Annotations',label:'Room name',fontSize:20,x:p.x,y:p.y,angle:0,showLabel:true};state.items.push(i);state.layers.Annotations=true;selected=i.id;modeSet('select');layers();properties();$('prop-label').focus();$('prop-label').select();status('Type a room name in the Label field. Drag the text to position it.');return;}
if(mode==='place'&&pending){checkpoint();const [label,cat,w,h,type]=pending;const i={id:uid(),label,category:cat,w,h,type,x:p.x,y:p.y,angle:0};state.items.push(i);state.layers[cat]=true;selected=i.id;modeSet('select');layers();properties();status(`${label} added. Drag to move; edit dimensions on the right.`);return;}
let el=e.target.closest('[data-id]');selected=el?.dataset.id||null;properties();render();if(selected){checkpoint();const i=state.items.find(i=>i.id===selected);drag={x:p.x,y:p.y,original:JSON.parse(JSON.stringify(i)),id:selected,vertex:e.target.dataset.vertex===undefined?null:Number(e.target.dataset.vertex)};$('canvas').setPointerCapture(e.pointerId);}});
$('canvas').addEventListener('pointermove',e=>{if(!drag){if(mode==='polygon'){hover=snapPoint(locationOf(e),e);render();}return;}if(drag.pan){const scale=view.w/$('canvas').getBoundingClientRect().width;view.x=drag.view.x-(e.clientX-drag.x)*scale;view.y=drag.view.y-(e.clientY-drag.y)*scale;}else{const p=locationOf(e),dx=p.x-drag.x,dy=p.y-drag.y,i=state.items.find(i=>i.id===drag.id);if(i.type==='polygon'&&drag.vertex!==null){const q=snapPoint(p,e,i.id);const next=i.points.map((v,n)=>n===drag.vertex?{x:q.x,y:q.y}:v);if(validPolygon(next))i.points=next;}else if(i.points)i.points=drag.original.points.map(q=>({x:q.x+dx,y:q.y+dy}));else{i.x=drag.original.x+dx;i.y=drag.original.y+dy;}}render();});
for(const ev of ['pointerup','pointercancel'])$('canvas').addEventListener(ev,()=>{drag=null;});
function zoom(f){const cx=view.x+view.w/2,cy=view.y+view.h/2;let w=Math.max(state.width*.15,Math.min(state.width*5,view.w*f)),ratio=w/view.w;view={x:cx-w/2,y:cy-view.h*ratio/2,w,h:view.h*ratio};render();}
$('canvas').addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?1.1:1/1.1);},{passive:false});
$('categories').onclick=e=>{const c=e.target.closest('[data-category]');if(c){category=c.dataset.category;library();}};
$('catalog').onclick=e=>{const b=e.target.closest('[data-catalog]');if(!b)return;if(!state.calibrated){status('Set a known wall measurement before placing items.');startCalibration();return;}const item=catalog[Number(b.dataset.catalog)];modeSet(item[4]==='polygon'?'polygon':item[4]==='route'?'route':'place');pending=item;status(item[4]==='polygon'?'Click corners to draw the shape. Grid and corner snapping are on. Finish with Enter or click the first corner.':item[4]==='route'?'Click points to draw the route. Double-click or Enter to finish.':`Click the plan to place ${item[0].toLowerCase()} (${item[2]} × ${item[3]} m).`);};
$('layers').onchange=e=>{if(!e.target.dataset.layer)return;checkpoint();state.layers[e.target.dataset.layer]=e.target.checked;if(state.items.find(i=>i.id===selected)?.category===e.target.dataset.layer&&!e.target.checked){selected=null;properties();}render();};
function startCalibration(){modeSet('calibrate');status('Click the two ends of a wall whose length you know.');}
$('calibrate').onclick=$('calibrate-side').onclick=startCalibration;$('select').onclick=()=>{modeSet('select');status('Select an item, or choose one from the library.');};$('text-tool').onclick=()=>{modeSet('text');status('Click the plan to add a room label.');};$('measure').onclick=()=>{if(!state.calibrated){startCalibration();return;}modeSet('measure');status('Click the two endpoints to add a permanent measurement label.');};
$('scale-dialog').addEventListener('close',()=>{if($('scale-dialog').returnValue==='apply'&&points.length===2){const metres=Number($('wall-length').value),distance=Math.hypot(points[1].x-points[0].x,points[1].y-points[0].y);if(metres>0&&metres<=1000){checkpoint();state.ppm=distance/metres;state.calibrated=true;status(`Scale set from a ${metres} m wall.`);}}modeSet('select');});
for(const [field,key] of [['label','label'],['width','w'],['height','h'],['angle','angle']])$('prop-'+field).onchange=e=>{const i=state.items.find(i=>i.id===selected);if(!i)return;let value=key==='label'?e.target.value.trim():Number(e.target.value);if(key!=='label'&&(!Number.isFinite(value)||(key!=='angle'&&(value<.05||value>50)))){properties();return;}checkpoint();i[key]=value;render();};
$('prop-wall-thickness').onchange=e=>{const i=state.items.find(i=>i.id===selected),v=Number(e.target.value);if(!i?.room)return;if(!Number.isFinite(v)||v<.03||v>1){properties();return;}checkpoint();i.wallThickness=v;render();};
$('prop-font-size').onchange=e=>{const i=state.items.find(i=>i.id===selected),size=Number(e.target.value);if(!i||i.type!=='text')return;if(!Number.isFinite(size)||size<8||size>100){properties();return;}checkpoint();i.fontSize=size;render();};
$('prop-show-label').onchange=e=>{const i=state.items.find(i=>i.id===selected);if(!i)return;checkpoint();i.showLabel=e.target.checked;render();};
function remove(){if(!selected)return;checkpoint();state.items=state.items.filter(i=>i.id!==selected);selected=null;properties();render();}
$('delete').onclick=remove;$('duplicate').onclick=()=>{const i=state.items.find(i=>i.id===selected);if(!i)return;checkpoint();const copy=JSON.parse(JSON.stringify(i));copy.id=uid();if(copy.points)copy.points.forEach(p=>{p.x+=20;p.y+=20;});else{copy.x+=20;copy.y+=20;}state.items.push(copy);selected=copy.id;properties();render();};
function restore(){selected=null;modeSet('select');$('project-name').value=state.name;$('opacity').value=state.opacity;layers();properties();render();}
function undo(){if(!history.length)return;future.push(JSON.stringify(state));state=JSON.parse(history.pop());restore();}function redo(){if(!future.length)return;history.push(JSON.stringify(state));state=JSON.parse(future.pop());restore();}
$('undo').onclick=undo;$('redo').onclick=redo;$('fit').onclick=fit;$('zoom-in').onclick=()=>zoom(1/1.2);$('zoom-out').onclick=()=>zoom(1.2);$('opacity').oninput=e=>{state.opacity=Number(e.target.value);render();};$('project-name').onchange=e=>{checkpoint();state.name=e.target.value||'My HDB home';};
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||document.querySelector('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if(e.key==='Escape'){modeSet('select');status('Select an item, or choose one from the library.');}else if(e.key==='Enter'&&mode==='polygon'){e.preventDefault();finishPolygon();}else if(e.key==='Backspace'&&mode==='polygon'){e.preventDefault();points.pop();render();}else if(e.key==='Enter'&&mode==='route')finishRoute();else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove();}else if(e.key.toLowerCase()==='r'){const i=state.items.find(i=>i.id===selected);if(i&&!i.points){checkpoint();i.angle=(i.angle+15)%360;properties();render();}}else if(e.key.toLowerCase()==='v')modeSet('select');});
function readFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('Image could not be decoded.'));img.src=src;});}
$('upload').onclick=()=>$('image-file').click();$('image-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Please choose a PNG, JPG or WebP image.');if(file.size>25*1024*1024)throw new Error('Please choose an image smaller than 25 MB.');const img=await loadImage(await readFile(file));if(state.items.length&&!confirm('Replace the floor plan and clear placed items? Save your project first if you need a copy.'))return;const ratio=Math.min(1,2200/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*ratio);c.height=Math.round(img.height*ratio);c.getContext('2d').drawImage(img,0,0,c.width,c.height);checkpoint();state.image=c.toDataURL('image/png');state.width=c.width;state.height=c.height;state.demo=false;state.calibrated=false;state.items=[];selected=null;state.opacity=.8;restore();fit();startCalibration();}catch(err){status(err.message);}};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
const filename=()=>state.name.replace(/[^a-z0-9_-]+/gi,'-')||'floor-plan';
$('save').onclick=()=>{download(new Blob([JSON.stringify(state)],{type:'application/json'}),filename()+'.json');status('Project saved with your image, scale and editable items.');};$('open').onclick=()=>$('project-file').click();
function validProject(s){const num=(v,min,max)=>Number.isFinite(v)&&v>=min&&v<=max;if(!s||s.version!==1||typeof s.name!=='string'||s.name.length>200||!num(s.width,1,10000)||!num(s.height,1,10000)||!num(s.ppm,.001,1000000)||!num(s.opacity,0,1)||typeof s.demo!=='boolean'||typeof s.calibrated!=='boolean'||!s.layers||!Object.keys(colors).every(k=>typeof s.layers[k]==='boolean'||(['Annotations','Kitchen','Carpentry','Appliances','Windows & Doors','Walls'].includes(k)&&s.layers[k]===undefined))||!Array.isArray(s.items)||s.items.length>3000)return false;if(s.image!==null&&(typeof s.image!=='string'||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(s.image)))return false;const ids=new Set();return s.items.every(i=>{if(!i||typeof i.id!=='string'||!/^[\w-]+$/.test(i.id)||ids.has(i.id)||(!Object.hasOwn(colors,i.category)&&i.category!=='Aircon')||typeof i.label!=='string'||i.label.length>200||(i.showLabel!==undefined&&typeof i.showLabel!=='boolean')||(i.overhead!==undefined&&typeof i.overhead!=='boolean')||(i.hotWater!==undefined&&typeof i.hotWater!=='boolean')||(i.room!==undefined&&typeof i.room!=='boolean')||(i.wallThickness!==undefined&&!num(i.wallThickness,.03,1)))return false;ids.add(i.id);if(i.type==='text')return i.category==='Annotations'&&num(i.fontSize,8,100)&&num(i.x,-100000,100000)&&num(i.y,-100000,100000)&&num(i.angle,-100000,100000);if(i.type==='polygon')return ['Furniture','Carpentry','Walls'].includes(i.category)&&Array.isArray(i.points)&&i.points.length<=100&&i.points.every(p=>p&&num(p.x,-100000,100000)&&num(p.y,-100000,100000))&&validPolygon(i.points);if(i.points)return Array.isArray(i.points)&&i.points.length>=2&&i.points.length<=1000&&i.points.every(p=>num(p.x,-100000,100000)&&num(p.y,-100000,100000));return (i.type==='round'||catalog.some(c=>c[4]===i.type&&c[4]!=='route'))&&num(i.w,.05,50)&&num(i.h,.05,50)&&num(i.x,-100000,100000)&&num(i.y,-100000,100000)&&num(i.angle,-100000,100000);});}
$('project-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>40*1024*1024)throw new Error('Project is too large (40 MB maximum).');const next=JSON.parse(await file.text());if(!validProject(next))throw new Error('This is not a valid Flatspace project.');if(next.image)await loadImage(next.image);if(state.items.length&&!confirm('Open this project and replace the current workspace?'))return;checkpoint();state=next;state.layers.Annotations??=true;state.layers.Kitchen??=true;migrateCarpentry(state);migrateAppliances(state);migrateOpenings(state);state.layers.Walls??=true;restore();fit();status('Project opened.');}catch(err){status(err.message);}};
function exportSvg(){const bar=state.ppm,legend=Object.keys(colors).filter(c=>state.layers[c]&&state.items.some(i=>i.category===c));return `<svg xmlns="${NS}" width="${state.width+80}" height="${state.height+170}" viewBox="-40 -75 ${state.width+80} ${state.height+170}"><rect x="-40" y="-75" width="${state.width+80}" height="${state.height+170}" fill="white"/><text x="0" y="-32" font-family="Arial" font-size="24" fill="#22352f">${esc(state.name)}</text>${art(false)}<g transform="translate(0 ${state.height+35})" font-family="Arial" font-size="12" fill="#4c6155">${state.calibrated?`<path d="M0 -5V5M0 0H${bar}M${bar} -5V5" stroke="#4c6155" stroke-width="2"/><text x="${bar+10}" y="4">1 metre${state.demo?' · illustrative demo':''}</text>`:'<text>Scale not calibrated</text>'}<text y="36">${esc(legend.join('  ·  '))}</text><text x="${state.width}" y="36" text-anchor="end" fill="#8b988f">FLATSPACE · Planning reference</text></g></svg>`;}
async function exportPng(){const svg=exportSvg(),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml;charset=utf-8'}));try{const img=await loadImage(url),c=document.createElement('canvas'),scale=Math.min(Number($('resolution').value),8000/Math.max(img.width,img.height));c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Unable to export this image.')),'image/png'));}finally{URL.revokeObjectURL(url);}}
$('export').onclick=()=>$('export-dialog').showModal();$('close-export').onclick=()=>$('export-dialog').close();$('png').onclick=async()=>{try{$('png').disabled=true;download(await exportPng(),filename()+'.png');$('export-dialog').close();status('High-resolution PNG exported.');}catch(e){status(e.message);}finally{$('png').disabled=false;}};
$('print').onclick=async()=>{try{$('print').disabled=true;const blob=await exportPng(),url=URL.createObjectURL(blob),img=await loadImage(url);document.querySelector('.print-image')?.remove();img.className='print-image';img.alt=state.name;document.body.append(img);$('export-dialog').close();window.print();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){status(e.message);}finally{$('print').disabled=false;}};
window.addEventListener('beforeunload',e=>{if(history.length){e.preventDefault();e.returnValue='';}});

function migrateOpenings(s){s.layers['Windows & Doors']??=s.layers.Furniture;for(const i of s.items){if(i.type==='door'&&i.category==='Furniture')i.category='Windows & Doors';}}
function migrateAppliances(s){s.layers.Appliances??=s.layers.Aircon??true;for(const i of s.items){if(i.category==='Kitchen'&&i.label==='Tall unit'&&i.type==='cabinet')i.type='tallunit';if(i.category==='Plumbing'&&i.label==='Hot water pipe')i.hotWater=true;if(i.category==='Aircon')i.category='Appliances';if(i.category==='Appliances'&&i.label==='Compressor'&&i.type==='aircon')i.type='compressor';if(i.category==='Furniture'&&i.label==='Washing machine'&&i.type==='round'){i.category='Appliances';i.type='washer';}if(i.category==='Furniture'&&i.label==='TV console'&&i.type==='cabinet')i.type='console';if(i.category==='Furniture'&&i.label==='Bedside table'&&i.type==='cabinet')i.type='smalltable';}delete s.layers.Aircon;}
function migrateCarpentry(s){s.layers.Carpentry??=s.layers.Furniture;for(const i of s.items){if(i.category==='Furniture'&&(i.type==='carpentry'||i.type==='polygon'))i.category='Carpentry';}}
function polygonBounds(ps){return {minX:Math.min(...ps.map(p=>p.x)),maxX:Math.max(...ps.map(p=>p.x)),minY:Math.min(...ps.map(p=>p.y)),maxY:Math.max(...ps.map(p=>p.y))};}
function validPolygon(ps){if(ps.length<3||ps.length>100)return false;const cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x),on=(a,b,c)=>Math.abs(cross(a,b,c))<1e-7&&c.x>=Math.min(a.x,b.x)-1e-7&&c.x<=Math.max(a.x,b.x)+1e-7&&c.y>=Math.min(a.y,b.y)-1e-7&&c.y<=Math.max(a.y,b.y)+1e-7;let area=0;for(let i=0;i<ps.length;i++){let a=ps[i],b=ps[(i+1)%ps.length];if(Math.hypot(a.x-b.x,a.y-b.y)<.01)return false;area+=a.x*b.y-b.x*a.y;for(let j=i+1;j<ps.length;j++){if(j===i+1||(i===0&&j===ps.length-1))continue;let c=ps[j],d=ps[(j+1)%ps.length];if((cross(a,b,c)*cross(a,b,d)<0&&cross(c,d,a)*cross(c,d,b)<0)||on(a,b,c)||on(a,b,d)||on(c,d,a)||on(c,d,b))return false;}}return Math.abs(area)>.01;}
function snapTolerance(){const m=$('canvas').getScreenCTM();return m&&m.a?10/Math.abs(m.a):view.w/80;}
function objectCorners(i){if(i.points)return i.points;if(!i.w||!i.h)return [];const a=(i.angle||0)*Math.PI/180;return [[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,y])=>{x*=i.w*state.ppm/2;y*=i.h*state.ppm/2;return {x:i.x+x*Math.cos(a)-y*Math.sin(a),y:i.y+x*Math.sin(a)+y*Math.cos(a)};});}
function snapPoint(raw,e={},exclude=null){let p={x:raw.x,y:raw.y};const bypass=e.ctrlKey||e.metaKey,step=state.ppm*(Number($('snap-step').value)||.1),tol=snapTolerance();if(!bypass&&$('snap-grid').checked){p.x=Math.round(p.x/step)*step;p.y=Math.round(p.y/step)*step;}if(!bypass&&$('snap-corners').checked){const targets=[...points,...state.items.filter(i=>i.id!==exclude&&state.layers[i.category]).flatMap(objectCorners)];let best=tol;for(const t of targets){const dist=Math.hypot(raw.x-t.x,raw.y-t.y);if(dist<best){best=dist;p={x:t.x,y:t.y};}}}if(e.shiftKey&&points.length){const last=points.at(-1);if(Math.abs(p.x-last.x)>=Math.abs(p.y-last.y))p.y=last.y;else p.x=last.x;}p.x=Math.max(0,Math.min(state.width,p.x));p.y=Math.max(0,Math.min(state.height,p.y));return p;}
function finishPolygon(){if(!validPolygon(points)){status('Use at least three corners without crossing edges. Undo a corner to correct the shape.');return;}checkpoint();const i={id:uid(),type:'polygon',category:pending?.[1]||'Carpentry',label:pending?.[1]==='Walls'?pending[0]:pending?.[5]?'Overhead storage':'Custom carpentry',room:!!pending?.[6],wallThickness:.1,overhead:!!pending?.[5],showLabel:pending?.[1]!=='Walls',points:points.map(p=>({...p}))};state.items.push(i);state.layers[i.category]=true;selected=i.id;modeSet('select');layers();properties();status(i.category==='Walls'?'Wall layout added. Drag edges to move the whole shape or drag corners to resize the room.':'Carpentry added. Drag the shape or its corners to adjust it.');}
function polygonPreview(){if(mode!=='polygon'||!hover)return '';const ps=[...points,hover],last=points.at(-1);return `<g pointer-events="none"><polyline points="${ps.map(p=>p.x+','+p.y).join(' ')}" fill="#65887918" stroke="#17694d" stroke-width="2" stroke-dasharray="${pending?.[5]?'1 5':'5 4'}" stroke-linecap="round"/><circle cx="${hover.x}" cy="${hover.y}" r="${snapTolerance()/2}" fill="white" stroke="#17694d" stroke-width="2"/>${last?`<text x="${(last.x+hover.x)/2}" y="${(last.y+hover.y)/2-10}" font-size="13" fill="#17694d" stroke="white" stroke-width="3" paint-order="stroke">${(Math.hypot(hover.x-last.x,hover.y-last.y)/state.ppm).toFixed(2)} m</text>`:''}</g>`;}
$('finish-polygon').onclick=finishPolygon;$('undo-corner').onclick=()=>{points.pop();render();};

state.items=[{id:uid(),label:'Sofa',category:'Furniture',w:2.1,h:.9,type:'sofa',x:480,y:630,angle:0},{id:uid(),label:'Queen bed',category:'Furniture',w:1.52,h:1.9,type:'bed',x:810,y:184,angle:90},{id:uid(),label:'Dining table',category:'Furniture',w:1.4,h:.8,type:'table',x:483,y:360,angle:0}];

// Additional small storage pieces requested for the furniture library.
catalog.push(['Short open bookshelf','Furniture',1.0,.3,'openshelf'],['Shoe cabinet','Furniture',1.0,.35,'shoecabinet']);
const symbolBase=symbol;
symbol=(type,w,h,c,showText=true)=>{let body='';const rect=(x,y,a,b,r=2)=>`<rect x="${x}" y="${y}" width="${a}" height="${b}" rx="${r}"/>`;
if(type==='openshelf')body=rect(0,0,w,h,1)+[.25,.5,.75].map(y=>`<path d="M0 ${h*y}H${w}"/>`).join('')+`<path d="M${w*.08} 0V${h}M${w*.92} 0V${h}"/>`;
else if(type==='shoecabinet')body=rect(0,0,w,h,2)+[.2,.5,.8].map(y=>`<path d="M${w*.1} ${h*y}H${w*.9}"/>`).join('')+`<path d="M${w*.46} ${h*.12}h${w*.08}M${w*.46} ${h*.42}h${w*.08}M${w*.46} ${h*.72}h${w*.08}"/>`;
else {const old=symbolBase(type,w,h,c,showText);return old;}return `<g fill="${c}18" stroke="${c}" stroke-width="1.7" vector-effect="non-scaling-stroke">${body}</g>`;};
catalog.push(['Sliding door','Windows & Doors',1.8,.15,'slidingdoor'],['Bi-fold door','Windows & Doors',1.8,.15,'bifold']);
const symbolBase2=symbol;
symbol=(type,w,h,c,showText=true)=>{if(type==='slidingdoor'){const p=w/2;return `<g fill="${c}18" stroke="${c}" stroke-width="1.7" vector-effect="non-scaling-stroke"><rect width="${w}" height="${h}" fill="none"/><path d="M0 ${h/2}H${w}M${p} 0V${h}"/><path d="M${p*.75} ${h*.5}h${p*.35}l-${p*.08} -${h*.18}m${p*.08} ${h*.18}l-${p*.08} ${h*.18}M${p*1.25} ${h*.5}h-${p*.35}l${p*.08} -${h*.18}m-${p*.08} ${h*.18}l${p*.08} ${h*.18}" fill="none"/></g>`;}if(type==='bifold'){const p=w/2;return `<g fill="${c}18" stroke="${c}" stroke-width="1.7" vector-effect="non-scaling-stroke"><rect width="${w}" height="${h}" fill="none"/><path d="M${p} 0V${h}M0 ${h/2}H${w}"/><path d="M${p*.45} ${h*.5}L${p*.9} ${h*.18}M${p*.45} ${h*.5}L${p*.9} ${h*.82}M${p*1.55} ${h*.5}L${p*1.1} ${h*.18}M${p*1.55} ${h*.5}L${p*1.1} ${h*.82}" fill="none" stroke-dasharray="4 3"/></g>`;}return symbolBase2(type,w,h,c,showText);};
catalog.push(['Baby cot','Furniture',1.25,.7,'babycot']);
const symbolBase3=symbol;
symbol=(type,w,h,c,showText=true)=>{if(type==='babycot')return `<g fill="${c}18" stroke="${c}" stroke-width="1.7" vector-effect="non-scaling-stroke"><rect width="${w}" height="${h}" rx="3"/><rect x="${w*.1}" y="${h*.14}" width="${w*.8}" height="${h*.72}" rx="5" fill="white"/><path d="M${w*.2} ${h*.1}V${h*.9}M${w*.35} ${h*.1}V${h*.9}M${w*.5} ${h*.1}V${h*.9}M${w*.65} ${h*.1}V${h*.9}M${w*.8} ${h*.1}V${h*.9}"/><circle cx="${w*.1}" cy="${h*.1}" r="3"/><circle cx="${w*.9}" cy="${h*.1}" r="3"/><circle cx="${w*.1}" cy="${h*.9}" r="3"/><circle cx="${w*.9}" cy="${h*.9}" r="3"/></g>`;return symbolBase3(type,w,h,c,showText);};
catalog.push(['Floor mattress','Furniture',1.4,2.0,'floor-mattress']);
const symbolBase4=symbol;
symbol=(type,w,h,c,showText=true)=>{if(type==='floor-mattress')return `<g fill="${c}18" stroke="${c}" stroke-width="1.7" vector-effect="non-scaling-stroke"><rect width="${w}" height="${h}" rx="${Math.min(w,h)*.08}"/><rect x="${w*.1}" y="${h*.08}" width="${w*.8}" height="${h*.2}" rx="${h*.08}" fill="white"/><path d="M${w*.08} ${h*.38}H${w*.92}M${w*.08} ${h*.58}H${w*.92}M${w*.08} ${h*.78}H${w*.92}" stroke-dasharray="3 4"/></g>`;return symbolBase4(type,w,h,c,showText);};
colors['Pet Areas']='#b26f62';
state.layers['Pet Areas']??=true;
const validProjectBase=validProject;
validProject=s=>{s.layers??={};s.layers['Pet Areas']??=true;return validProjectBase(s);};
catalog.push(['Fenced dog area','Pet Areas',1.8,1.4,'dogarea']);
const symbolBase5=symbol;
symbol=(type,w,h,c,showText=true)=>{if(type==='dogarea')return `<g fill="${c}10" stroke="${c}" stroke-width="2" vector-effect="non-scaling-stroke"><rect x="2" y="2" width="${w-4}" height="${h-4}" rx="4" fill="none" stroke-dasharray="7 5"/><path d="M${w*.18} ${h*.2}V${h*.8}M${w*.36} ${h*.2}V${h*.8}M${w*.54} ${h*.2}V${h*.8}M${w*.72} ${h*.2}V${h*.8}M${w*.18} ${h*.2}H${w*.72}" opacity=".6"/><g transform="translate(${w*.5} ${h*.55})" fill="${c}" stroke="none"><ellipse cx="0" cy="${h*.08}" rx="${w*.11}" ry="${h*.14}"/><ellipse cx="-${w*.13}" cy="-${h*.08}" rx="${w*.055}" ry="${h*.085}"/><ellipse cx="-${w*.035}" cy="-${h*.15}" rx="${w*.055}" ry="${h*.085}"/><ellipse cx="${w*.06}" cy="-${h*.15}" rx="${w*.055}" ry="${h*.085}"/><ellipse cx="${w*.15}" cy="-${h*.08}" rx="${w*.055}" ry="${h*.085}"/></g></g>`;return symbolBase5(type,w,h,c,showText);};
library();layers();properties();fit();
