'use strict';
const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
const colors={Furniture:'#658879',Electrical:'#cf9750',Plumbing:'#4f91b7',Aircon:'#7e80ae',Lighting:'#c7a43c',Measurements:'#718078'};
const catalog=[['Sofa','Furniture',2.1,.9,'sofa'],['Queen bed','Furniture',1.52,1.9,'bed'],['Single bed','Furniture',.91,1.9,'bed'],['Dining table','Furniture',1.4,.8,'table'],['Wardrobe','Furniture',1.8,.6,'cabinet'],['Desk','Furniture',1.2,.6,'table'],['Armchair','Furniture',.8,.8,'sofa'],['Fridge','Furniture',.7,.7,'cabinet'],['TV console','Furniture',1.8,.4,'cabinet'],['Washing machine','Furniture',.6,.6,'round'],['Power socket','Electrical',.18,.18,'socket'],['Light switch','Electrical',.15,.15,'switch'],['Data point','Electrical',.18,.18,'data'],['DB box','Electrical',.4,.15,'cabinet'],['Cable route','Electrical',0,0,'route'],['Sink','Plumbing',.6,.5,'sink'],['Toilet','Plumbing',.4,.7,'toilet'],['Shower','Plumbing',.9,.9,'shower'],['Water point','Plumbing',.15,.15,'round'],['Cold water pipe','Plumbing',0,0,'route'],['Hot water pipe','Plumbing',0,0,'route'],['Indoor unit','Aircon',.9,.23,'aircon'],['Compressor','Aircon',.85,.35,'aircon'],['Refrigerant route','Aircon',0,0,'route'],['Ceiling light','Lighting',.3,.3,'light'],['Downlight','Lighting',.12,.12,'light'],['Pendant','Lighting',.4,.4,'light'],['LED strip','Lighting',0,0,'route']];
let state={version:1,name:'My HDB home',width:1000,height:850,ppm:100,calibrated:true,demo:true,image:null,opacity:.8,items:[],layers:Object.fromEntries(Object.keys(colors).map(k=>[k,true]))};
let selected=null,category='Furniture',mode='select',pending=null,points=[],view={x:-100,y:-70,w:1200,h:990},drag=null,history=[],future=[];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const status=s=>$('status').textContent=s;
function checkpoint(){history.push(JSON.stringify(state));if(history.length>40)history.shift();future=[];}
function modeSet(m){mode=m;points=[];pending=null;$('select').classList.toggle('active',m==='select');$('calibrate').classList.toggle('active',m==='calibrate');$('measure').classList.toggle('active',m==='measure');$('canvas').style.cursor=m==='select'?'default':'crosshair';render();}
function symbol(type,w,h,c){let body='';const rect=(x,y,a,b,r=2)=>`<rect x="${x}" y="${y}" width="${a}" height="${b}" rx="${r}"/>`;
if(type==='sofa')body=rect(0,0,w,h,7)+rect(w*.1,h*.12,w*.8,h*.25)+`<path d="M${w/2} ${h*.4}v${h*.52}M${w*.1} ${h*.42}v${h*.5}M${w*.9} ${h*.42}v${h*.5}"/>`;
else if(type==='bed')body=rect(0,0,w,h,3)+rect(w*.08,h*.06,w*.38,h*.2)+rect(w*.54,h*.06,w*.38,h*.2)+`<path d="M0 ${h*.34}H${w}M${w*.08} ${h*.38}v${h*.55}h${w*.84}v-${h*.55}"/>`;
else if(type==='table')body=rect(0,0,w,h,10)+`<path d="M${w*.15} 0v${h}M${w*.85} 0v${h}" opacity=".3"/>`;
else if(type==='cabinet')body=rect(0,0,w,h)+`<path d="M${w/2} 0v${h}M${w*.43} ${h*.4}v${h*.2}M${w*.57} ${h*.4}v${h*.2}"/>`;
else if(type==='aircon')body=rect(0,0,w,h,4)+`<path d="M${w*.1} ${h*.65}H${w*.9}M${w*.1} ${h*.8}H${w*.9}"/>`;
else if(type==='sink')body=rect(0,0,w,h,5)+rect(w*.12,h*.2,w*.76,h*.68,7)+`<path d="M${w/2} 0v${h*.3}"/>`;
else if(type==='toilet')body=rect(0,0,w,h*.3)+`<ellipse cx="${w/2}" cy="${h*.64}" rx="${w*.43}" ry="${h*.34}"/>`;
else if(type==='shower')body=rect(0,0,w,h)+`<path d="M0 0L${w} ${h}M${w} 0L0 ${h}" opacity=".5"/>`;
else {body=`<ellipse cx="${w/2}" cy="${h/2}" rx="${w*.46}" ry="${h*.46}"/>`;if(type==='light')body+=`<path d="M${w*.18} ${h*.18}L${w*.82} ${h*.82}M${w*.82} ${h*.18}L${w*.18} ${h*.82}"/>`;if(type==='socket')body+=`<path d="M${w*.35} ${h*.3}v${h*.4}M${w*.65} ${h*.3}v${h*.4}"/>`;if(type==='switch'||type==='data')body+=`<text x="${w/2}" y="${h*.68}" font-size="${h*.5}" text-anchor="middle" stroke="none" fill="${c}">${type==='switch'?'S':'D'}</text>`;}
return `<g fill="${c}18" stroke="${c}" stroke-width="1.7" vector-effect="non-scaling-stroke">${body}</g>`;}
function demoPlan(){return `<rect width="1000" height="850" fill="white"/><g fill="#f7f8f5" stroke="#58675e" stroke-width="8"><path d="M80 90H920V730H80Z"/><path d="M80 350H340V90M340 350V490M340 570V730M80 530H250M310 530H340M340 280H560M640 280H920M650 90V280M760 280V450H920M650 280V400M650 480V730M650 520H920"/></g><g stroke="#a8b9b0" stroke-width="3" fill="none"><path d="M145 90h125m100 0h210m135 0h125M920 550v130M80 570v90M410 730h170"/><path d="M340 490a80 80 0 0 1-80 80h80M560 280a80 80 0 0 0 80 80v-80M650 400a80 80 0 0 1 80 80h-80" stroke-width="1.5"/></g><g font-family="Arial,sans-serif" font-size="13" fill="#8a978f" text-anchor="middle" letter-spacing="2"><text x="210" y="215">BEDROOM 2</text><text x="493" y="185">BEDROOM 3</text><text x="785" y="185">MAIN BEDROOM</text><text x="810" y="380">BATH</text><text x="210" y="445">KITCHEN</text><text x="210" y="640">SERVICE YARD</text><text x="495" y="475">LIVING / DINING</text><text x="785" y="620">ENTRY</text></g>`;}
function itemSvg(i,selection=true){const c=colors[i.category];if(i.points){let d=i.points.map((p,n)=>(n?'L':'M')+p.x+' '+p.y).join(' ');const length=i.points.slice(1).reduce((s,p,n)=>s+Math.hypot(p.x-i.points[n].x,p.y-i.points[n].y),0)/state.ppm;const p=i.points[Math.floor(i.points.length/2)];return `<g data-id="${i.id}"><path d="${d}" stroke="transparent" stroke-width="18" fill="none"/><path d="${d}" stroke="${selection&&i.id===selected?'#17694d':c}" stroke-width="${i.category==='Measurements'?2:4}" fill="none" stroke-linejoin="round" ${i.label==='Hot water pipe'?'stroke-dasharray="9 5"':''}/>${i.points.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="3" fill="${c}"/>`).join('')}<text x="${p.x+8}" y="${p.y-10}" font-family="Arial" font-size="12" fill="${c}" stroke="white" stroke-width="3" paint-order="stroke">${esc(i.label)} · ${length.toFixed(2)} m</text></g>`;}
const w=i.w*state.ppm,h=i.h*state.ppm;return `<g data-id="${i.id}" transform="translate(${i.x} ${i.y}) rotate(${i.angle})"><rect x="${-w/2-5}" y="${-h/2-5}" width="${w+10}" height="${h+10}" rx="5" fill="transparent" ${selection&&selected===i.id?'stroke="#17694d" stroke-width="2" stroke-dasharray="5 3"':''}/><g transform="translate(${-w/2} ${-h/2})">${symbol(i.type,w,h,c)}</g><text x="0" y="${h/2+17}" text-anchor="middle" font-family="Arial" font-size="11" fill="#53675b" stroke="white" stroke-width="3" paint-order="stroke">${esc(i.label)}</text></g>`;}
function art(selection=true){return `<rect width="${state.width}" height="${state.height}" fill="white"/><g opacity="${state.opacity}">${state.image?`<image href="${state.image}" width="${state.width}" height="${state.height}"/>`:demoPlan()}</g>${state.items.filter(i=>state.layers[i.category]).map(i=>itemSvg(i,selection)).join('')}`;}
function render(){const svg=$('canvas');svg.setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`);svg.innerHTML=art()+ (points.length?`<polyline points="${points.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="#17694d" stroke-width="3"/>${points.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="5" fill="#17694d"/>`).join('')}`:'');$('zoom-label').textContent=Math.round((state.width+200)/view.w*100)+'%';$('undo').disabled=!history.length;$('redo').disabled=!future.length;$('plan-state').textContent=state.demo?'Illustrative 4-room plan':'Your uploaded floor plan';$('scale-status').textContent=(state.demo?'Demo scale':state.calibrated?'Calibrated':'Scale not set')+' · '+state.ppm.toFixed(1)+' px / m';$('scale-title').textContent=state.demo?'Demo scale':state.calibrated?'Scale calibrated':'Set your scale';$('scale-description').textContent=state.calibrated&&!state.demo?'Furniture and measurements now use your calibrated wall length.':'Upload your own plan and calibrate it with a known wall measurement.';}
function library(){ $('categories').innerHTML=Object.keys(colors).filter(c=>c!=='Measurements').map(c=>`<button class="${c===category?'active':''}" data-category="${c}">${c}</button>`).join('');const entries=catalog.filter(i=>i[1]===category);$('item-count').textContent=entries.length+' ITEMS';$('catalog').innerHTML=entries.map(i=>`<button data-catalog="${catalog.indexOf(i)}" title="${i[4]==='route'?'Draw a route':`${i[2]} × ${i[3]} m`}"><svg viewBox="0 0 65 40">${i[4]==='route'?`<path d="M8 32V12H52V30" fill="none" stroke="${colors[category]}" stroke-width="2"/>`:`<g transform="translate(12 3)">${symbol(i[4],40,32,colors[category])}</g>`}</svg>${i[0]}</button>`).join('');}
function layers(){ $('layers').innerHTML=Object.keys(colors).map(c=>`<label class="layer"><span><i class="layer-color" style="background:${colors[c]}"></i>${c}</span><input type="checkbox" data-layer="${c}" ${state.layers[c]?'checked':''} aria-label="Show ${c}"></label>`).join('');}
function properties(){const i=state.items.find(i=>i.id===selected);$('properties').hidden=!i;$('empty-selection').hidden=!!i;if(!i)return;$('prop-label').value=i.label;for(const [key,field] of [['w','width'],['h','height'],['angle','angle']]){$('prop-'+field).value=i[key]??0;$('prop-'+field).disabled=!!i.points;}$('route-length').textContent=i.points?'Drag the route to move it. Delete and redraw to change its shape.':'';}
function fit(){view={x:-70,y:-65,w:state.width+140,h:state.height+130};render();}
function locationOf(e){let p=$('canvas').createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform($('canvas').getScreenCTM().inverse());}
function finishRoute(){if(points.length<2){status('Add at least two route points.');return;}checkpoint();const i={id:uid(),label:pending?.[0]||'Measurement',category:pending?.[1]||'Measurements',points:points.map(p=>({x:p.x,y:p.y}))};state.items.push(i);selected=i.id;modeSet('select');properties();status('Route added. Select it to move, rename or delete.');}
$('canvas').addEventListener('pointerdown',e=>{if(e.button!==0&&e.button!==1)return;let p=locationOf(e);if(e.button===1||e.altKey){drag={pan:true,x:e.clientX,y:e.clientY,view:{...view}};$('canvas').setPointerCapture(e.pointerId);e.preventDefault();return;}if(p.x<0||p.y<0||p.x>state.width||p.y>state.height)return;
if(mode==='calibrate'||mode==='measure'||mode==='route'){if(e.detail===2&&mode==='route'){finishRoute();return;}points.push({x:p.x,y:p.y});render();if(mode==='calibrate'&&points.length===2){if(Math.hypot(points[1].x-points[0].x,points[1].y-points[0].y)<5){points=[];render();status('Choose two distinct points on a wall.');return;}$('scale-dialog').showModal();}else if(mode==='measure'&&points.length===2)finishRoute();else status(mode==='route'?'Click to add bends. Double-click or press Enter to finish.':'Click the other end of the wall.');return;}
if(mode==='place'&&pending){checkpoint();const [label,cat,w,h,type]=pending;const i={id:uid(),label,category:cat,w,h,type,x:p.x,y:p.y,angle:0};state.items.push(i);state.layers[cat]=true;selected=i.id;modeSet('select');layers();properties();status(`${label} added. Drag to move; edit dimensions on the right.`);return;}
let el=e.target.closest('[data-id]');selected=el?.dataset.id||null;properties();render();if(selected){checkpoint();const i=state.items.find(i=>i.id===selected);drag={x:p.x,y:p.y,original:JSON.parse(JSON.stringify(i)),id:selected};$('canvas').setPointerCapture(e.pointerId);}});
$('canvas').addEventListener('pointermove',e=>{if(!drag)return;if(drag.pan){const scale=view.w/$('canvas').getBoundingClientRect().width;view.x=drag.view.x-(e.clientX-drag.x)*scale;view.y=drag.view.y-(e.clientY-drag.y)*scale;}else{const p=locationOf(e),dx=p.x-drag.x,dy=p.y-drag.y,i=state.items.find(i=>i.id===drag.id);if(i.points)i.points=drag.original.points.map(q=>({x:q.x+dx,y:q.y+dy}));else{i.x=drag.original.x+dx;i.y=drag.original.y+dy;}}render();});
for(const ev of ['pointerup','pointercancel'])$('canvas').addEventListener(ev,()=>{drag=null;});
function zoom(f){const cx=view.x+view.w/2,cy=view.y+view.h/2;let w=Math.max(state.width*.15,Math.min(state.width*5,view.w*f)),ratio=w/view.w;view={x:cx-w/2,y:cy-view.h*ratio/2,w,h:view.h*ratio};render();}
$('canvas').addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?1.1:1/1.1);},{passive:false});
$('categories').onclick=e=>{const c=e.target.closest('[data-category]');if(c){category=c.dataset.category;library();}};
$('catalog').onclick=e=>{const b=e.target.closest('[data-catalog]');if(!b)return;if(!state.calibrated){status('Set a known wall measurement before placing items.');startCalibration();return;}const item=catalog[Number(b.dataset.catalog)];modeSet(item[4]==='route'?'route':'place');pending=item;status(item[4]==='route'?'Click points to draw the route. Double-click or Enter to finish.':`Click the plan to place ${item[0].toLowerCase()} (${item[2]} × ${item[3]} m).`);};
$('layers').onchange=e=>{if(!e.target.dataset.layer)return;checkpoint();state.layers[e.target.dataset.layer]=e.target.checked;if(state.items.find(i=>i.id===selected)?.category===e.target.dataset.layer&&!e.target.checked){selected=null;properties();}render();};
function startCalibration(){modeSet('calibrate');status('Click the two ends of a wall whose length you know.');}
$('calibrate').onclick=$('calibrate-side').onclick=startCalibration;$('select').onclick=()=>{modeSet('select');status('Select an item, or choose one from the library.');};$('measure').onclick=()=>{if(!state.calibrated){startCalibration();return;}modeSet('measure');status('Click two points to measure their distance.');};
$('scale-dialog').addEventListener('close',()=>{if($('scale-dialog').returnValue==='apply'&&points.length===2){const metres=Number($('wall-length').value),distance=Math.hypot(points[1].x-points[0].x,points[1].y-points[0].y);if(metres>0&&metres<=1000){checkpoint();state.ppm=distance/metres;state.calibrated=true;status(`Scale set from a ${metres} m wall.`);}}modeSet('select');});
for(const [field,key] of [['label','label'],['width','w'],['height','h'],['angle','angle']])$('prop-'+field).onchange=e=>{const i=state.items.find(i=>i.id===selected);if(!i)return;let value=key==='label'?e.target.value.trim():Number(e.target.value);if(key!=='label'&&(!Number.isFinite(value)||(key!=='angle'&&(value<.05||value>50)))){properties();return;}checkpoint();i[key]=value;render();};
function remove(){if(!selected)return;checkpoint();state.items=state.items.filter(i=>i.id!==selected);selected=null;properties();render();}
$('delete').onclick=remove;$('duplicate').onclick=()=>{const i=state.items.find(i=>i.id===selected);if(!i)return;checkpoint();const copy=JSON.parse(JSON.stringify(i));copy.id=uid();if(copy.points)copy.points.forEach(p=>{p.x+=20;p.y+=20;});else{copy.x+=20;copy.y+=20;}state.items.push(copy);selected=copy.id;properties();render();};
function restore(){selected=null;modeSet('select');$('project-name').value=state.name;$('opacity').value=state.opacity;layers();properties();render();}
function undo(){if(!history.length)return;future.push(JSON.stringify(state));state=JSON.parse(history.pop());restore();}function redo(){if(!future.length)return;history.push(JSON.stringify(state));state=JSON.parse(future.pop());restore();}
$('undo').onclick=undo;$('redo').onclick=redo;$('fit').onclick=fit;$('zoom-in').onclick=()=>zoom(1/1.2);$('zoom-out').onclick=()=>zoom(1.2);$('opacity').oninput=e=>{state.opacity=Number(e.target.value);render();};$('project-name').onchange=e=>{checkpoint();state.name=e.target.value||'My HDB home';};
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||document.querySelector('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if(e.key==='Escape'){modeSet('select');status('Select an item, or choose one from the library.');}else if(e.key==='Enter'&&mode==='route')finishRoute();else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove();}else if(e.key.toLowerCase()==='r'){const i=state.items.find(i=>i.id===selected);if(i&&!i.points){checkpoint();i.angle=(i.angle+15)%360;properties();render();}}else if(e.key.toLowerCase()==='v')modeSet('select');});
function readFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('Image could not be decoded.'));img.src=src;});}
$('upload').onclick=()=>$('image-file').click();$('image-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Please choose a PNG, JPG or WebP image.');if(file.size>25*1024*1024)throw new Error('Please choose an image smaller than 25 MB.');const img=await loadImage(await readFile(file));if(state.items.length&&!confirm('Replace the floor plan and clear placed items? Save your project first if you need a copy.'))return;const ratio=Math.min(1,2200/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*ratio);c.height=Math.round(img.height*ratio);c.getContext('2d').drawImage(img,0,0,c.width,c.height);checkpoint();state.image=c.toDataURL('image/png');state.width=c.width;state.height=c.height;state.demo=false;state.calibrated=false;state.items=[];selected=null;state.opacity=.8;restore();fit();startCalibration();}catch(err){status(err.message);}};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
const filename=()=>state.name.replace(/[^a-z0-9_-]+/gi,'-')||'floor-plan';
$('save').onclick=()=>{download(new Blob([JSON.stringify(state)],{type:'application/json'}),filename()+'.json');status('Project saved with your image, scale and editable items.');};$('open').onclick=()=>$('project-file').click();
function validProject(s){const num=(v,min,max)=>Number.isFinite(v)&&v>=min&&v<=max;if(!s||s.version!==1||typeof s.name!=='string'||s.name.length>200||!num(s.width,1,10000)||!num(s.height,1,10000)||!num(s.ppm,.001,1000000)||!num(s.opacity,0,1)||typeof s.demo!=='boolean'||typeof s.calibrated!=='boolean'||!s.layers||!Object.keys(colors).every(k=>typeof s.layers[k]==='boolean')||!Array.isArray(s.items)||s.items.length>3000)return false;if(s.image!==null&&(typeof s.image!=='string'||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(s.image)))return false;const ids=new Set();return s.items.every(i=>{if(!i||typeof i.id!=='string'||!/^[\w-]+$/.test(i.id)||ids.has(i.id)||!Object.hasOwn(colors,i.category)||typeof i.label!=='string'||i.label.length>200)return false;ids.add(i.id);if(i.points)return Array.isArray(i.points)&&i.points.length>=2&&i.points.length<=1000&&i.points.every(p=>num(p.x,-100000,100000)&&num(p.y,-100000,100000));return catalog.some(c=>c[4]===i.type&&c[4]!=='route')&&num(i.w,.05,50)&&num(i.h,.05,50)&&num(i.x,-100000,100000)&&num(i.y,-100000,100000)&&num(i.angle,-100000,100000);});}
$('project-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>40*1024*1024)throw new Error('Project is too large (40 MB maximum).');const next=JSON.parse(await file.text());if(!validProject(next))throw new Error('This is not a valid Flatspace project.');if(next.image)await loadImage(next.image);if(state.items.length&&!confirm('Open this project and replace the current workspace?'))return;checkpoint();state=next;restore();fit();status('Project opened.');}catch(err){status(err.message);}};
function exportSvg(){const bar=state.ppm,legend=Object.keys(colors).filter(c=>state.layers[c]&&state.items.some(i=>i.category===c));return `<svg xmlns="${NS}" width="${state.width+80}" height="${state.height+170}" viewBox="-40 -75 ${state.width+80} ${state.height+170}"><rect x="-40" y="-75" width="${state.width+80}" height="${state.height+170}" fill="white"/><text x="0" y="-32" font-family="Arial" font-size="24" fill="#22352f">${esc(state.name)}</text>${art(false)}<g transform="translate(0 ${state.height+35})" font-family="Arial" font-size="12" fill="#4c6155">${state.calibrated?`<path d="M0 -5V5M0 0H${bar}M${bar} -5V5" stroke="#4c6155" stroke-width="2"/><text x="${bar+10}" y="4">1 metre${state.demo?' · illustrative demo':''}</text>`:'<text>Scale not calibrated</text>'}<text y="36">${esc(legend.join('  ·  '))}</text><text x="${state.width}" y="36" text-anchor="end" fill="#8b988f">FLATSPACE · Planning reference</text></g></svg>`;}
async function exportPng(){const svg=exportSvg(),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml;charset=utf-8'}));try{const img=await loadImage(url),c=document.createElement('canvas'),scale=Math.min(Number($('resolution').value),8000/Math.max(img.width,img.height));c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Unable to export this image.')),'image/png'));}finally{URL.revokeObjectURL(url);}}
$('export').onclick=()=>$('export-dialog').showModal();$('close-export').onclick=()=>$('export-dialog').close();$('png').onclick=async()=>{try{$('png').disabled=true;download(await exportPng(),filename()+'.png');$('export-dialog').close();status('High-resolution PNG exported.');}catch(e){status(e.message);}finally{$('png').disabled=false;}};
$('print').onclick=async()=>{try{$('print').disabled=true;const blob=await exportPng(),url=URL.createObjectURL(blob),img=await loadImage(url);document.querySelector('.print-image')?.remove();img.className='print-image';img.alt=state.name;document.body.append(img);$('export-dialog').close();window.print();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){status(e.message);}finally{$('print').disabled=false;}};
window.addEventListener('beforeunload',e=>{if(history.length){e.preventDefault();e.returnValue='';}});
state.items=[{id:uid(),label:'Sofa',category:'Furniture',w:2.1,h:.9,type:'sofa',x:480,y:630,angle:0},{id:uid(),label:'Queen bed',category:'Furniture',w:1.52,h:1.9,type:'bed',x:810,y:184,angle:90},{id:uid(),label:'Dining table',category:'Furniture',w:1.4,h:.8,type:'table',x:483,y:360,angle:0}];library();layers();properties();fit();
